### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by HotzFish** [VigiZhang/afl-dyninst#1]
There's an error when I run "cmake .. && make"
```
g++ -g -Wall -O3 -std=c++11 -L/home/oit/Desktop/dyninst-ins/lib \
		-L/usr/local/lib \
		-o afl-dyninst afl-dyninst.o \
		-lcommon \
		-liberty \
		-ldyninstAPI 
/usr/bin/ld: afl-dyninst.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//home/oit/Desktop/dyninst-ins/lib/libboost_system.so.1.61.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [afl-dyninst] Error 1
```

**Comment by HotzFish** [comment]
[ 25%] Linking CXX executable afl-dyninst
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `findFuncByName(BPatch_image*, char*)':
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:134: undefined reference to `BPatch_image::findFunction(char const*, std::vector<BPatch_function*, std::allocator<BPatch_function*> >&, bool, bool, bool)'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `insertCallbackToAddr(BPatch_addressSpace*, BPatch_image*, BPatch_function*, BPatch_module*, BPatch_function*)':
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:145: undefined reference to `BPatch_function::findPoint(eBPatch_procedureLocation)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:154: undefined reference to `BPatch_funcCallExpr::BPatch_funcCallExpr(BPatch_function const&, std::vector<BPatch_snippet*, std::allocator<BPatch_snippet*> > const&)'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `~BPatch_funcCallExpr':
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `insertBBCallback(BPatch_addressSpace*, BPatch_image*, BPatch_function*, BPatch_function*, char*, unsigned int*)':
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:170: undefined reference to `BPatch_function::getCFG()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:178: undefined reference to `BPatch_flowGraph::getAllBasicBlocks(std::set<BPatch_basicBlock*, std::less<BPatch_basicBlock*>, std::allocator<BPatch_basicBlock*> >&)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:182: undefined reference to `BPatch_basicBlock::size() const'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:188: undefined reference to `BPatch_basicBlock::isEntryBlock() const'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:206: undefined reference to `BPatch_basicBlock::findEntryPoint()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:207: undefined reference to `BPatch_basicBlock::getStartAddress() const'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:211: undefined reference to `BPatch_basicBlock::size() const'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:223: undefined reference to `BPatch_constExpr::BPatch_constExpr(int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:226: undefined reference to `BPatch_funcCallExpr::BPatch_funcCallExpr(BPatch_function const&, std::vector<BPatch_snippet*, std::allocator<BPatch_snippet*> > const&)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:227: undefined reference to `BPatch_funcCallExpr::BPatch_funcCallExpr(BPatch_function const&, std::vector<BPatch_snippet*, std::allocator<BPatch_snippet*> > const&)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:228: undefined reference to `BPatch_funcCallExpr::BPatch_funcCallExpr(BPatch_function const&, std::vector<BPatch_snippet*, std::allocator<BPatch_snippet*> > const&)'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `~BPatch_funcCallExpr':
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `~BPatch_constExpr':
/usr/local/include/BPatch_snippet.h:230: undefined reference to `BPatch_snippet::~BPatch_snippet()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `insertBBCallback(BPatch_addressSpace*, BPatch_image*, BPatch_function*, BPatch_function*, char*, unsigned int*)':
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:192: undefined reference to `BPatch_basicBlock::getSources(std::vector<BPatch_basicBlock*, std::allocator<BPatch_basicBlock*> >&)'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `~BPatch_constExpr':
/usr/local/include/BPatch_snippet.h:230: undefined reference to `BPatch_snippet::~BPatch_snippet()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `~BPatch_funcCallExpr':
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
/usr/local/include/BPatch_snippet.h:289: undefined reference to `BPatch_snippet::~BPatch_snippet()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `BPatch_constExpr::~BPatch_constExpr()':
/usr/local/include/BPatch_snippet.h:230: undefined reference to `BPatch_snippet::~BPatch_snippet()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o:/usr/local/include/BPatch_snippet.h:230: more undefined references to `BPatch_snippet::~BPatch_snippet()' follow
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `main':
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:260: undefined reference to `BPatch::BPatch()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:262: undefined reference to `BPatch::openBinary(char const*, bool)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:269: undefined reference to `BPatch_addressSpace::getImage()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:271: undefined reference to `BPatch_image::getModules()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:290: undefined reference to `BPatch_module::getName(char*, int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:295: undefined reference to `BPatch_module::getProcedures(bool)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:299: undefined reference to `BPatch_function::getName(char*, int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:384: undefined reference to `BPatch_module::findFunctionByEntry(unsigned long)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:405: undefined reference to `BPatch_module::getName(char*, int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:428: undefined reference to `BPatch_module::getName(char*, int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:429: undefined reference to `BPatch_module::isSharedLib()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:437: undefined reference to `BPatch_module::getProcedures(bool)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:444: undefined reference to `BPatch_function::getName(char*, int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:471: undefined reference to `BPatch_module::findFunctionByEntry(unsigned long)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:484: undefined reference to `BPatch_binaryEdit::writeFile(char const*)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:495: undefined reference to `BPatch::~BPatch()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:495: undefined reference to `BPatch::~BPatch()'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:368: undefined reference to `BPatch_module::findFunction(char const*, std::vector<BPatch_function*, std::allocator<BPatch_function*> >&, bool, bool, bool, bool)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:373: undefined reference to `BPatch_module::getName(char*, int)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:386: undefined reference to `BPatch_module::findFunctionByEntry(unsigned long)'
/home/oit/Desktop/afl-dyninst-master/afl-dyninst.cc:357: undefined reference to `BPatch_module::findFunction(char const*, std::vector<BPatch_function*, std::allocator<BPatch_function*> >&, bool, bool, bool, bool)'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o: In function `__static_initialization_and_destruction_0':
/usr/local/include/boost/system/error_code.hpp:221: undefined reference to `boost::system::generic_category()'
/usr/local/include/boost/system/error_code.hpp:222: undefined reference to `boost::system::generic_category()'
/usr/local/include/boost/system/error_code.hpp:223: undefined reference to `boost::system::system_category()'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o:(.rodata._ZTI19BPatch_funcCallExpr[_ZTI19BPatch_funcCallExpr]+0x8): undefined reference to `typeinfo for BPatch_snippet'
CMakeFiles/afl-dyninst.dir/afl-dyninst.cc.o:(.rodata._ZTI16BPatch_constExpr[_ZTI16BPatch_constExpr]+0x8): undefined reference to `typeinfo for BPatch_snippet'
collect2: error: ld returned 1 exit status
make[2]: *** [afl-dyninst] Error 1
make[1]: *** [CMakeFiles/afl-dyninst.dir/all] Error 2
make: *** [all] Error 2

**Comment by VigiZhang** [comment]
please check library path
`ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012`

**Comment by VigiZhang** [comment]
commit [4eec2fa](https://github.com/VigiZhang/afl-dyninst/commit/4eec2fabbd5d0e2081ac1fd6c264526b50c460aa) fixed this potential link path error.

**Comment by HotzFish** [comment]
谢谢
